spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.port=8080
spring.jackson.default-property-inclusion=non_null

# Gemini API Keys (Comma separated)
gemini.api.keys=${GEMINI_API_KEY:default_missing_key}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
