spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.port=8080
spring.jackson.default-property-inclusion=non_null

# Gemini API Key (Can be overridden by env variable GEMINI_API_KEY)
gemini.api.key=${GEMINI_API_KEY:default_missing_key}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
